
#define MAX_INFINITE_TOKENS  5
#define MAX_FINITE_TOKENS 30
#define DEFAULT_EXPIRATION 30
#define DEFAULT_ALLOW_RENEW false

//#define SAVE_TOKEN_TRANSACTIONS
#define SAVE_USER_TRANSACTIONS

#define DEFAULT_PRODUCTION_PORT 80
#define ALL_ENTRIES_LOWER
#define START_ROOT_NAME "root"
#define ONE_MEGA_BYTES 1048576
#define MAX_PROFILE_PICTURE (ONE_MEGA_BYTES *2)
#define START_ROOT_PASSWORD "root"
#define ID_SIZE 15
#define SHA_SIZE 15

