
#define MAX_INFINITE_TOKENS  5
#define MAX_FINITE_TOKENS 30
#define DEFAULT_EXPIRATION 30
#define DEFAULT_ALLOW_RENEW false
#define DEFAULT_PRODUCTION_PORT 80
#define START_ROOT_NAME "root"
#define START_ROOT_PASSWORD "root"

#define SHA_SIZE 15
