
#define USE_OBSERVALITY
#define MAX_REQUESTS_SAVE 1000
#define REQUESTS_OBSERVER_PATH "data/requests"
#define INCLUDE_URL_OBSERVER
#define INCLUDE_QUERY_PARAMS_OBSERVER
#define INCLUDE_HEADDERS_OBSERVER
#define INCLUDE_REQUEST_CONTENT
#define INCLUDE_RESPONSE_CONTENT
#define INCLUDE_RESPONSE_HEADDERS
