#define TOKEN_KEY "token"
#define CODE_KEY "code"
#define EXPIRATION_KEY "expiration"
#define CREATION_KEY "creation"
#define FINITE_TOKENS_KEY "finite_tokens"
#define INFINITE_TOKENS_KEY "infinite_tokens"
#define ALLOW_RENEW_KEY "allow_renew"
#define LAST_UPDATE_KEY "last_update"
#define USERNAME_KEY "username"
#define MESSAGE_KEY "message"
#define EMAIL_KEY "email"
#define EXPIRED_RESPONSE "expired"
#define IS_ROOT_KEY "root"

#define TERMINATED_APLICATION "Application Terminated"
#define USER_CREATED "User Created"
#define NEVER_EXPIRATION "never"
#define TOKEN_CREATED "Token Created"
#define TOKEN_REMOVED "Token Removed"