#define END_ROUTE "/end"
#define CREATE_TOKEN_ROUTE "/create_token"
#define REMOVE_TOKEN_ROUTE "/remove_token"
#define GET_SELF_PROPS_ROUTE  "/get_self_props"
#define CREATE_USER_ROUTE "/create_user"
#define LIST_USERS "/list_users"
#define REMOVE_USER_ROUTE "/remove_user"
#define MODIFY_SELF_PROPS_ROUTE "/modify_self_props"
#define MODIFY_USER_PROPS_ROUTE "/modify_user_props"

#define GET_USER_PROPS_ROUTE "/get_user_props"
