#include "create_token/create_token.c"
#include "remove_token/remove_token.c"
#include "get_self_props/get_self_props.c"
#include "modify_self_props/modify_self_props.c"
#include "self_remove/self_remove.c"